background = "Background knowledge:\nMoral norm refers to a rule of conduct generally observed by most people in everyday situations. Moral conflict refers to a situation where a person is engaged in some decision-making process and he is faced with two conflicting moral norms. However, one of these norms has a higher priority, so moral conflict can be resolved by adhering this norm.\n\n"

generation_task_description = "Task description:\nYour task is to generate a high-quality moral conflict following my instructions. I will provide you with the beginning of the moral conflict, a moral norm, and the action corresponding to this norm. The detailed requirements are as follows:\n1. The moral conflict should be written in four parts: beginning(provided), background description, psychological description, and a fixed-format ending which is '{protagonist} is/was caught in a moral conflict between {brief description of norm} or {brief description of conflict-norm}'. \n2. The moral conflict should be fluent, concrete, realistic and limited to 60-100 words. \n3. The given norm should be one of two norms of this moral conflict. Additionally, if the protagonist adheres to the given norm, he or she should take the given action.\n4. The given norm holds a higher priority in the moral conflict, meaning that adhering to given norm is considered a more moral choice.\n5. The moral conflict you generate should not mention the two moral norms directly.\n6. In addition to the moral conflict, you must also provide the conflicting norm (conflict-norm) and its corresponding action (conflict-action).\n7. Output format:\nMoral conflict: [Moral conflict].\nConflict-norm: [Conflict-norm].\nConflict-action: [Conflict-action].\n\n"


generation_shot_1 = "Input:\nBeginning: Plato borrowed a knife from Paul to prepare dinner.\nNorm: Protecting others from harm is necessary.\nAction: Plato decides to hide the knife and return it later.\nOutput:\nMoral conflict: Plato borrowed a knife from Paul to prepare dinner. When he went to return it, he saw Paul in a heated argument with another person. The argument was intense, voices raised, and the atmosphere was thick with tension. Plato knew he should return the knife as promised, but he could not ignore the possibility that, in the heat of the moment, Paul might use the knife to escalate the situation. Plato was caught in a moral conflict between avoiding potential danger or keeping his promise.\nConflict-norm: Paying debts is important to maintain friendships.\nConflict-action: Plato returns the knife to the angry Paul."

generation_shot_2 = "Input:\nBeginning: Kent is watching his kids playing in the backyard of his house.\nNorm: It's responsible to keep children safe.\nAction: Kent installs cameras around his yard to look for intruders.\nOutput:\nMoral conflict: Kent is watching his kids playing in the backyard of his house. He noticed that a few older kids from the neighborhood often wandered near his yard, sometimes playing rough or engaging in risky behavior. Concerned about potential accidents, Kent wants to ensure his children’s safety by installing some cameras. However, he knows the cameras might make the older kids feel uncomfortable or unwelcome, possibly causing friction in the neighborhood. Kent is caught in a moral conflict between protecting his children or fostering a friendly neighborhood environment.\nConflict-norm: Maintaining a welcoming environment is essential for community harmony.\nConflict-action: Kent chooses not to install the cameras to keep the neighborhood atmosphere friendly."

generation_shot_3 = "Input:\nBeginning: Greg's mother has ordered him to clean his messy room.\nNorm: You should not shirk household chores.\nAction: Greg spends couple of hours cleaning his room.\nOutput:\nMoral conflict: Moral conflict: Greg's mother has ordered him to clean his messy room. Suddenly, his friend James shouts out the window, inviting him to play a new video game that has recently come out. Greg looked at the mess in his room, knowing that his mother expected it to be cleaned before she returned. Meanwhile, he thought about the fun he could have at James’s house, escaping the boredom of cleaning. Greg is caught in a moral conflict between fulfilling his responsibility at home or enjoying time with his friend.\nConflict-norm: Enjoying leisure time with friends is important for maintaining social connections. \nConflict-action: Greg leaves his room messy and goes to James’s house to play video games."

generation_shot_4 = "Input:\nBeginning: Sandra is visiting her cousin's house when she sees a doll she really likes.\nNorm: It is bad to steal from others.\nAction: Sandra asks her mother nicely if she can have a doll just like her cousin's.\nOutput:\nMoral conflict: Sandra is visiting her cousin's house when she sees a doll she really likes. Sandra had loved this doll for a long time but her mother refused to buy her one. She couldn’t stop thinking about the doll, feeling an urge to take it home with her. Sandra is caught in a moral conflict between respecting others' property or having a favourite toy.\nConflict-norm: Satisfying one's immediate desires is natural for personal happiness.\nConflict-action: Sandra secretly takes the doll home"

generation_shot_5 = "Input:\nBeginning: Tom has worked for the same company for the past thirty years.\nNorm: It's immoral to steal from a company.\nAction: Tom has a meeting with his boss to ask if he can get a raise.\nOutput:\nMoral conflict: Tom has worked for the same company for the past thirty years. Over the years, his responsibilities had increased without any corresponding raise. Now, Tom finds himself in a difficult financial situation and the stress of his financial troubles has begun to take a toll on his health and well-being. Tom is caught in a moral conflict between addressing his financial problems or maintaining his integrity.\nConflict-norm: It's essential to ensure your own well-being.\nConflict-action: Tom secretly takes office supplies to make money."

generation_shots = f"Examples:\n{generation_shot_1}\n\n{generation_shot_2}\n\n{generation_shot_3}\n\n{generation_shot_4}\n\n{generation_shot_5}\n\n"

instruction_4_generation = background + generation_task_description + generation_shots + "Input:\nBeginning: {Situation}\nNorm: {Norm}\nAction: {Moral_action}\nOutput:"


filtering_task_description = "Task description:\nYour task is to evaluate whether the data I provide meets the following conditions.\n\n"

filtering_conditions = "Conditions:\n1. Is the moral conflict fluent, concrete and realistic? \n2. Are norm_1 and norm_2 moral and generally accepted in real life?\n3. Does this moral conflict imply the semantics of both norm_1 and norm_2?\n4. Whether norm_1 has a higher priority in this moral conflict, i.e. compliance with norm_1 is the more ethical choice?\n5.  Does norm_1 correspond to action_1? Specifically, if norm_1 is followed, should action_1 be taken?\n6. Does norm_2 correspond to action_2? Specifically, if norm_2 is followed, should action_2 be taken?\n\n"

filtering_output_requirements = "Output requirements:\nEvaluate each condition individually, one by one. Output format:\nCondition 1: [Yes/No].\nCondition 2: [Yes/No].\nCondition 3: [Yes/No].\nCondition 4: [Yes/No].\nCondition 5: [Yes/No].\nCondition 6: [Yes/No].\n\n"

instruction_4_filtering = background + filtering_task_description + filtering_conditions + filtering_output_requirements + "Moral conflict: {Moral_conflict}.\nNorm_1: {Norm}.\nNorm_2: {Conflict-norm}.\nAction_1: {Action}.\nAction_2: {Conflict-action}.\n\n"



if __name__ == '__main__':
    print(instruction_4_filtering)
